const venues = [
  {name:'Paddle Ground Pickleball Court Cebu', region:'cebu', area:'Cebu City', courts:3, price:350, unit:'court/hr', tags:['indoor','lights','parking'], rating:4.8, hours:'7 AM–12 AM', address:'Sitio Ylaya, Talamban, Cebu City', featured:true},
  {name:'AfterHours Pickleball', region:'cebu', area:'Cebu City', courts:4, price:350, unit:'court/hr', tags:['indoor','lights'], rating:4.9, hours:'7 AM–12 AM', address:'J.King Warehouse Complex, Cebu City', featured:true},
  {name:'Prime Rally PH | Pickleball Courts Cebu', region:'cebu', area:'Cebu City', courts:4, price:350, unit:'court/hr', tags:['lights','parking','paddleRental'], rating:4.7, hours:'8 AM–2 AM', address:'L. Gabuya St, Cebu City'},
  {name:'Net and Paddle Pickleball Club', region:'cebu', area:'Cebu City', courts:4, price:400, unit:'court/hr', tags:['indoor','lights','parking','paddleRental','openPlay'], rating:4.5, hours:'8 AM–12 AM', address:'Tupas St, Cebu City'},
  {name:'Thirsty Pickle (SM Seaside Pickleball)', region:'cebu', area:'Cebu City', courts:4, price:400, unit:'court/hr', tags:['indoor','aircon','parking','cafe'], rating:4.5, hours:'8 AM–12 AM', address:'SM Seaside City, Cebu City'},
  {name:'Archangel Pickleball Center', region:'cebu', area:'Cebu City', courts:3, price:null, unit:'check venue', tags:['indoor','lights'], rating:4.5, hours:'Check venue', address:'Kasambagan, Cebu City'},
  {name:'Piknik Premier Pickleball', region:'cebu', area:'Cebu City', courts:4, price:null, unit:'check venue', tags:['indoor','lights','parking'], rating:4.8, hours:'Check venue', address:'A. Abellana Extension, Cebu City'},
  {name:'Dink n Lob Pickleball', region:'cebu', area:'Cebu City', courts:3, price:null, unit:'check venue', tags:['lights','openPlay'], rating:3.8, hours:'Split hours', address:'Cebu City'},
  {name:'VELOCITY PICKLEBALL HUB', region:'cebu', area:'Cebu City', courts:4, price:null, unit:'check venue', tags:['lights','parking','openPlay'], rating:3.7, hours:'7 AM–2 AM', address:'Gorordo Ave, Cebu City'},
  {name:'HQ Pickleball Cebu', region:'cebu', area:'Cebu City', courts:4, price:null, unit:'check venue', tags:['indoor','lights'], rating:3.3, hours:'24 hours', address:'Archbishop Reyes Ave, Cebu City'},
  {name:'Pickle at The Kiln', region:'cebu', area:'Mandaue', courts:4, price:550, unit:'court/hr', tags:['indoor','aircon','parking'], rating:null, hours:'7 AM–12 AM', address:'Hernan Cortes St, Banilad, Mandaue', featured:true},
  {name:'Royall Court Sports Center', region:'cebu', area:'Mandaue', courts:6, price:360, unit:'court/hr', tags:['indoor','aircon','parking','paddleRental'], rating:null, hours:'8 AM–12 AM', address:'E.O. Perez St, Subangdaku, Mandaue', featured:true},
  {name:'SMASH Sports Facilities', region:'cebu', area:'Mandaue', courts:3, price:500, unit:'court/hr', tags:['indoor','aircon','parking','paddleRental'], rating:null, hours:'7 AM–12 AM', address:'Near Guizo Barangay Hall, Mandaue'},
  {name:'State of Mind Cebu', region:'cebu', area:'Mandaue', courts:4, price:750, unit:'court/hr', tags:['indoor','aircon','parking'], rating:null, hours:'24 hours', address:'Banilad, Mandaue'},
  {name:'SweetSpot Pickleball Courts CEBU', region:'cebu', area:'Mandaue', courts:5, price:null, unit:'check venue', tags:['indoor','aircon','parking'], rating:3.7, hours:'Check venue', address:'HVG IT Park, Mandaue'},
  {name:'PUMPD Pickleball Cebu', region:'cebu', area:'Mandaue', courts:4, price:null, unit:'check venue', tags:['indoor','lights','parking','paddleRental'], rating:4.2, hours:'24 hours', address:'Lopez Jaena St, Subangdaku, Mandaue'},
  {name:'Lapu-Lapu City Cebu Pickleball Club', region:'cebu', area:'Lapu-Lapu', courts:2, price:null, unit:'check venue', tags:['outdoor','lights','parking','openPlay'], rating:5, hours:'6 AM–12 AM', address:'Provident Homes, Kinalumsan, Lapu-Lapu'},
  {name:'Solterra Dink Pickleball', region:'cebu', area:'Talisay', courts:4, price:null, unit:'check venue', tags:['lights','parking','openPlay'], rating:4.5, hours:'6 AM–12 AM', address:'Labuca, Talisay, Cebu'},
  {name:'The Courtside Cebu', region:'cebu', area:'Talisay', courts:3, price:null, unit:'check venue', tags:['indoor','lights','parking'], rating:4.8, hours:'10 AM–9 PM', address:'Starmall Talisay, Cebu'},
  {name:'J\'s Pickleball & Dine', region:'cebu', area:'Consolacion', courts:2, price:299, unit:'court/hr', tags:['lights','parking','cafe'], rating:null, hours:'24 hours', address:'Pob. Oriental, Consolacion'},
  {name:'GN COURTS', region:'cebu', area:'Consolacion', courts:3, price:300, unit:'court/hr', tags:['lights','parking'], rating:null, hours:'24 hours', address:'Casili, Consolacion'},
  {name:'AC DINK', region:'cebu', area:'Consolacion', courts:2, price:300, unit:'court/hr', tags:['lights','parking'], rating:null, hours:'24 hours', address:'Casili, Consolacion'},
  {name:'Dinktopia Court Hub', region:'cebu', area:'Consolacion', courts:4, price:300, unit:'court/hr', tags:['lights','parking'], rating:null, hours:'24 hours', address:'Cansaga, Consolacion'},
  {name:'B31G Badminton & Pickleball Courts', region:'cebu', area:'Consolacion', courts:6, price:400, unit:'court/hr', tags:['indoor','lights','parking'], rating:null, hours:'8 AM–12 AM', address:'Tayud, Consolacion'},
  {name:'ECCON PICKLEBALL', region:'cebu', area:'Consolacion', courts:2, price:250, unit:'court/hr', tags:['lights','parking'], rating:null, hours:'24 hours', address:'Garing, Consolacion'},
  {name:'Arena Athletics', region:'davao', area:'Davao City', courts:11, price:null, unit:'check venue', tags:['indoor','aircon','lights','parking','openPlay'], rating:null, hours:'Check venue', address:'Davao City'},
  {name:'PickleTown Davao', region:'davao', area:'Davao City', courts:10, price:null, unit:'check venue', tags:['indoor','aircon','lights','parking'], rating:null, hours:'Early–midnight', address:'Carmelite Road, Davao City'},
  {name:'Davao Pickleball at Matina Town Square', region:'davao', area:'Davao City', courts:4, price:150, unit:'player/session', tags:['outdoor','lights','openPlay','cafe'], rating:null, hours:'Check venue', address:'Matina Town Square, Davao City'},
  {name:'PicklePoint Iloilo', region:'iloilo', area:'Iloilo City', courts:6, price:400, unit:'court/hr', tags:['indoor','aircon','lights','parking','openPlay'], rating:null, hours:'Check venue', address:'Iloilo City'},
  {name:'Paddle Co.', region:'bacolod', area:'Bacolod', courts:4, price:400, unit:'player/session', tags:['indoor','lights','parking','openPlay'], rating:null, hours:'Check venue', address:'Bacolod City'}
];

const state={search:'',region:'cebu',areas:new Set(),price:null,keys:new Set(),sort:'recommended',theme:localStorage.getItem('pp-theme')||'dark'};
const $=id=>document.getElementById(id);
function areas(){return [...new Set(venues.filter(v=>state.region==='all'||v.region===state.region).map(v=>v.area))].sort()}
function money(v){return v.price==null?'Check venue':`₱${v.price.toLocaleString()}/${v.unit.includes('player')?'player':'hr'}`}
function card(v){const map=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(v.name+' '+v.address)}`;const tags=v.tags.map(t=>({indoor:'Indoor',outdoor:'Outdoor',aircon:'Aircon',lights:'Night lights',parking:'Parking',paddleRental:'Paddle rental',openPlay:'Open play',cafe:'Food / café'}[t]||t));const safeName=v.name.replaceAll("'",'&#39;');return `<article class="card"><div class="card-top"><div><span class="area">${v.area}</span><h3>${v.name}</h3></div>${v.featured?'<span class="featured">Featured</span>':''}</div><div class="details"><span>🏟 <b>${v.courts}</b> courts</span><span>💸 <b>${money(v)}</b></span><span>⏰ ${v.hours}</span>${v.rating?`<span>★ <b>${v.rating}</b></span>`:''}</div><div class="tags">${tags.map(x=>`<span>${x}</span>`).join('')}</div><p class="address">${v.address}</p><div class="card-actions"><a class="primary-btn" target="_blank" rel="noreferrer" href="${map}">Open in Maps</a><button class="secondary-btn" data-copy="${safeName}" type="button">Copy name</button></div></article>`}
function render(){
  const list=venues.filter(v=>{if(state.region!=='all'&&v.region!==state.region)return false;if(state.search&&!(v.name+' '+v.area+' '+v.address).toLowerCase().includes(state.search.toLowerCase()))return false;if(state.areas.size&&!state.areas.has(v.area))return false;if(state.price!==null&&(v.price==null||v.price>state.price))return false;for(const k of state.keys)if(!v.tags.includes(k))return false;return true}).sort((a,b)=>{if(state.sort==='price-low')return(a.price??99999)-(b.price??99999);if(state.sort==='price-high')return(b.price??-1)-(a.price??-1);if(state.sort==='courts-high')return b.courts-a.courts;if(state.sort==='name')return a.name.localeCompare(b.name);return(b.featured?1:0)-(a.featured?1:0)||(b.rating??0)-(a.rating??0)});
  $('results').innerHTML=list.map(card).join('');$('empty').hidden=list.length>0;$('resultMeta').textContent=`${list.length} venue${list.length===1?'':'s'} found · ${state.region==='all'?'Philippines':state.region==='cebu'?'Cebu':'selected region'}`;$('filterSummary').textContent=activeCount()?`${activeCount()} filters active`:'';
  $('stats').innerHTML=`<div><b>${venues.filter(v=>v.region==='cebu').length}</b><span>Cebu venues</span></div><div><b>${venues.filter(v=>v.region!=='cebu').length}</b><span>PH starter venues</span></div>`;
  $('areaChips').innerHTML=areas().map(a=>`<button class="chip ${state.areas.has(a)?'active':''}" data-area="${a}">${a}</button>`).join('')||'<span class="muted">Choose a region</span>';
  document.querySelectorAll('[data-area]').forEach(b=>b.onclick=()=>{state.areas.has(b.dataset.area)?state.areas.delete(b.dataset.area):state.areas.add(b.dataset.area);render()});
  document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);const old=b.textContent;b.textContent='Copied';setTimeout(()=>b.textContent=old,900)}catch{}});
}
function activeCount(){return(state.search?1:0)+(state.areas.size?1:0)+(state.price!==null?1:0)+state.keys.size+(state.region!=='cebu'?1:0)}
document.querySelectorAll('[data-price]').forEach(b=>b.onclick=()=>{const val=Number(b.dataset.price);state.price=state.price===val?null:val;document.querySelectorAll('[data-price]').forEach(x=>x.classList.toggle('active',Number(x.dataset.price)===state.price));render()});
document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{const k=b.dataset.key;state.keys.has(k)?state.keys.delete(k):state.keys.add(k);b.classList.toggle('active',state.keys.has(k));render()});
$('search').oninput=e=>{state.search=e.target.value;render()};$('region').onchange=e=>{state.region=e.target.value;state.areas.clear();render()};$('sort').onchange=e=>{state.sort=e.target.value;render()};
$('resetBtn').onclick=$('emptyReset').onclick=()=>{state.search='';state.region='cebu';state.areas.clear();state.price=null;state.keys.clear();state.sort='recommended';$('search').value='';$('region').value='cebu';$('sort').value='recommended';document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));render()};
$('themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';localStorage.setItem('pp-theme',state.theme);document.documentElement.dataset.theme=state.theme;$('themeBtn').textContent=state.theme==='dark'?'☼':'☾'};
$('locateBtn').onclick=()=>{if(!navigator.geolocation)return alert('Location is not available in this browser.');navigator.geolocation.getCurrentPosition(()=>alert('Location access is ready. Distance sorting can be added next.'),()=>alert('Please allow location access to enable nearby sorting.'))};
document.documentElement.dataset.theme=state.theme;$('themeBtn').textContent=state.theme==='dark'?'☼':'☾';render();
