const venues = [
  {name:'Paddle Ground Pickleball Court Cebu', region:'cebu', area:'Cebu City', courts:3, price:350, unit:'court/hr', tags:['indoor','lights','parking'], rating:4.8, hours:'7 AM–12 AM', address:'Sitio Ylaya, Talamban, Cebu City', phone:'', source:'Google listing', featured:true},
  {name:'AfterHours Pickleball', region:'cebu', area:'Cebu City', courts:4, price:350, unit:'court/hr', tags:['indoor','lights'], rating:4.9, hours:'7 AM–12 AM', address:'J.King Warehouse Complex, Cebu City', featured:true},
  {name:'Prime Rally PH | Pickleball Courts Cebu', region:'cebu', area:'Cebu City', courts:4, price:350, unit:'court/hr', tags:['lights','parking','paddleRental'], rating:4.7, hours:'8 AM–2 AM', address:'L. Gabuya St, Cebu City'},
  {name:'Net and Paddle Pickleball Club', region:'cebu', area:'Cebu City', courts:4, price:400, unit:'court/hr', tags:['indoor','lights','parking','paddleRental','openPlay'], rating:4.5, hours:'8 AM–12 AM', address:'Tupas St, Cebu City'},
  {name:'Thirsty Pickle (SM Seaside Pickleball)', region:'cebu', area:'Cebu City', courts:4, price:400, unit:'court/hr', tags:['indoor','aircon','parking','cafe'], rating:4.5, hours:'8 AM–12 AM', address:'SM Seaside City, Cebu City'},
  {name:'Archangel Pickleball Center', region:'cebu', area:'Cebu City', courts:3, price:400, unit:'court/hr', tags:['indoor','lights','parking','openPlay'], rating:4.5, hours:'8 AM–9 PM', address:'Gualandi Mission for the Deaf School, St. Michael Village, 5 Emerald, Brgy. Kasambagan, Cebu City 6000, Philippines', phone:'0915 434 9197', fb:'https://www.facebook.com/', source:'Cebu Pickle directory', notes:'Rate starts at ₱400/hr. Contact the venue to confirm the current booking process.', verified:'2026-09-10'},
  {name:'Piknik Premier Pickleball', region:'cebu', area:'Cebu City', courts:4, price:null, unit:'check venue', tags:['indoor','lights','parking'], rating:4.8, hours:'Check venue', address:'A. Abellana Extension, Cebu City', source:'Starter directory data'},
  {name:'Dink n Lob Pickleball', region:'cebu', area:'Cebu City', courts:3, price:null, unit:'check venue', tags:['lights','openPlay'], rating:3.8, hours:'Split hours', address:'Cebu City'},
  {name:'VELOCITY PICKLEBALL HUB', region:'cebu', area:'Cebu City', courts:4, price:null, unit:'check venue', tags:['lights','parking','openPlay'], rating:3.7, hours:'7 AM–2 AM', address:'Gorordo Ave, Cebu City'},
  {name:'HQ Pickleball Cebu', region:'cebu', area:'Cebu City', courts:7, price:600, unit:'court/hr', tags:['indoor','lights','parking','paddleRental','openPlay'], rating:3.5, hours:'24 hours', address:'Archbishop Reyes Ave, Cebu City 6000, Philippines', featured:true},
  {name:'Pickle at The Kiln', region:'cebu', area:'Mandaue', courts:4, price:550, unit:'court/hr', tags:['indoor','aircon','parking'], rating:null, hours:'7 AM–12 AM', address:'Hernan Cortes St, Banilad, Mandaue', featured:true},
  {name:'Royall Court Sports Center', region:'cebu', area:'Mandaue', courts:6, price:360, unit:'court/hr', tags:['indoor','parking','paddleRental','openPlay'], rating:null, hours:'8 AM–12 AM', address:'E.O. Perez Street, Subangdaku, Mandaue City, Cebu 6014, Philippines', featured:true},
  {name:'SMASH Sports Facilities', region:'cebu', area:'Mandaue', courts:3, price:500, unit:'court/hr', tags:['indoor','aircon','parking','paddleRental'], rating:null, hours:'7 AM–12 AM', address:'Near Guizo Barangay Hall, Mandaue'},
  {name:'State of Mind Cebu', region:'cebu', area:'Mandaue', courts:4, price:750, unit:'court/hr', tags:['indoor','aircon','parking'], rating:null, hours:'24 hours', address:'Banilad, Mandaue'},
  {name:'SweetSpot Pickleball Courts CEBU', region:'cebu', area:'Mandaue', courts:5, price:null, unit:'check venue', tags:['indoor','aircon','parking'], rating:3.7, hours:'Check venue', address:'HVG IT Park, Mandaue'},
  {name:'PUMPD Pickleball Cebu', region:'cebu', area:'Mandaue', courts:4, price:null, unit:'check venue', tags:['indoor','lights','parking','paddleRental'], rating:4.2, hours:'24 hours', address:'Lopez Jaena St, Subangdaku, Mandaue'},
  {name:'Lapu-Lapu City Cebu Pickleball Club', region:'cebu', area:'Lapu-Lapu', courts:2, price:null, unit:'check venue', tags:['outdoor','lights','parking','openPlay'], rating:5, hours:'6 AM–12 AM', address:'Provident Homes, Kinalumsan, Lapu-Lapu'},
  {name:'Solterra Dink Pickleball', region:'cebu', area:'Talisay', courts:4, price:null, unit:'check venue', tags:['lights','parking','openPlay'], rating:4.5, hours:'6 AM–12 AM', address:'Labuca, Talisay, Cebu'},
  {name:'The Courtside Cebu', region:'cebu', area:'Talisay', courts:4, price:400, unit:'court/hr', tags:['indoor','lights','parking','paddleRental','openPlay'], rating:4.8, hours:'10 AM–9 PM', address:'2F Starmall Cebu South Road, Talisay City, Cebu 6045, Philippines'},
  {name:'J\'s Pickleball & Dine', region:'cebu', area:'Consolacion', courts:2, price:299, unit:'court/hr', tags:['lights','parking','cafe'], rating:null, hours:'24 hours', address:'Pob. Oriental, Consolacion'},
  {name:'GN COURTS', region:'cebu', area:'Consolacion', courts:3, price:300, unit:'court/hr', tags:['lights','parking'], rating:null, hours:'24 hours', address:'Casili, Consolacion'},
  {name:'AC DINK', region:'cebu', area:'Consolacion', courts:2, price:300, unit:'court/hr', tags:['lights','parking'], rating:null, hours:'24 hours', address:'Casili, Consolacion'},
  {name:'Dinktopia Court Hub', region:'cebu', area:'Consolacion', courts:4, price:300, unit:'court/hr', tags:['lights','parking'], rating:null, hours:'24 hours', address:'Cansaga, Consolacion'},
  {name:'B31G Badminton & Pickleball Courts', region:'cebu', area:'Consolacion', courts:6, price:400, unit:'court/hr', tags:['indoor','lights','parking'], rating:null, hours:'8 AM–12 AM', address:'Tayud, Consolacion'},
  {name:'ECCON PICKLEBALL', region:'cebu', area:'Consolacion', courts:2, price:250, unit:'court/hr', tags:['lights','parking'], rating:null, hours:'24 hours', address:'Garing, Consolacion'},
  {name:'Pickle Yard — Cebu', region:'cebu', area:'Minglanilla', courts:1, price:450, unit:'court/hr', tags:['outdoor','openPlay'], rating:null, hours:'7 AM–10 PM', address:'Estaca I, Brgy. Tunghaan, Minglanilla, Cebu, Philippines', featured:true},
  {name:'SOotK Pickleball Hub (Stay Out of the Kitchen!)', region:'cebu', area:'Cebu City', courts:3, price:250, unit:'court/hr', tags:['outdoor','lights','parking','openPlay'], rating:4.8, hours:'4 PM–1 AM', address:'Siakoy Street, Brgy. Lahug, inside Regie’s Lechon House, Cebu City 6000, Philippines'},
  {name:'Andot Pickle Court', region:'cebu', area:'Cebu City', courts:2, price:450, unit:'court/hr', tags:['indoor','outdoor'], rating:4.7, hours:'6 AM–12 AM', address:'38-B Jade St., Buena Hills, Guadalupe, Cebu City, Cebu, Philippines'},
  {name:'PickleShatt Court', region:'cebu', area:'Mandaue', courts:1, price:null, unit:'check venue', tags:['outdoor','cafe'], rating:null, hours:'24 hours', address:'Z. Estrera St., Tabok, Mandaue City, Cebu 6014, Philippines'},
  {name:'BTC Pickleball Lapu-Lapu', region:'cebu', area:'Lapu-Lapu', courts:6, price:500, unit:'court/hr', tags:['outdoor','lights','parking','paddleRental'], rating:null, hours:'Check venue', address:'Pool Street, Lapu-Lapu City, Cebu, Philippines'},
  {name:'Arena Athletics', region:'davao', area:'Davao City', courts:11, price:null, unit:'check venue', tags:['indoor','aircon','lights','parking','openPlay'], rating:null, hours:'Check venue', address:'Davao City'},
  {name:'PickleTown Davao', region:'davao', area:'Davao City', courts:10, price:null, unit:'check venue', tags:['indoor','aircon','lights','parking'], rating:null, hours:'Early–midnight', address:'Carmelite Road, Davao City'},
  {name:'Davao Pickleball at Matina Town Square', region:'davao', area:'Davao City', courts:4, price:150, unit:'player/session', tags:['outdoor','lights','openPlay','cafe'], rating:null, hours:'Check venue', address:'Matina Town Square, Davao City'},
  {name:'PicklePoint Iloilo', region:'iloilo', area:'Iloilo City', courts:6, price:400, unit:'court/hr', tags:['indoor','aircon','lights','parking','openPlay'], rating:null, hours:'Check venue', address:'Iloilo City'},
  {name:'Paddle Co.', region:'bacolod', area:'Bacolod', courts:4, price:400, unit:'player/session', tags:['indoor','lights','parking','openPlay'], rating:null, hours:'Check venue', address:'Bacolod City'}
];

const detailOverrides={
 'HQ Pickleball Cebu':{phone:'0917 701 9131 / 0945 378 2090',email:'hqpickleballcebu@gmail.com',fb:'https://www.facebook.com/profile.php?id=61585259447279',instagram:'https://www.instagram.com/hqpickleballcebu/',booking:'https://app.sports360.ph/sportshub/hq-pickleball-cebu',website:'https://app.sports360.ph/sportshub/hq-pickleball-cebu',source:'Cebu Pickleball Courts + Dinky',verified:'2026-09-10',notes:'Current sources conflict on court count, setup, and pricing. Verify live booking before visiting.'},
 'CitiLoft Pickleball':{phone:'0954 226 9782',fb:'https://www.facebook.com/CitiLoftOne/',booking:'https://www.metrocebu.com/reservations',source:'Cebu Pickleball Courts',verified:'2026-09-10'},
 'Qusina PIQLE QLUB Pickleball Court':{phone:'0946 100 7777',email:'qusina@mybucketlist.ph',fb:'https://www.facebook.com/profile.php?id=100080588204828',booking:'https://app.sports360.ph/sportshub/qusina-piqle-qlub',website:'https://app.sports360.ph/sportshub/qusina-piqle-qlub',source:'Cebu Pickleball Courts',verified:'2026-09-10',notes:'₱300/hr 6 AM–4 PM and ₱500/hr 4 PM–6 AM.'},
 'Royall Court Sports Center':{phone:'0953 914 0194 / 0905 129 8804',fb:'https://www.facebook.com/p/Royall-Court-Sports-Center-61572140673865/',booking:'https://www.dinky.ph/courts/royall-court-sports-center',source:'Cebu Pickleball Courts + Dinky',verified:'2026-09-10',notes:'Current published rate is ₱360/hr effective September 1, 2026.'},
 'Power Play Cebu':{fb:'https://www.facebook.com/profile.php?id=61591109639385',instagram:'https://www.instagram.com/powerplay.cebu/',booking:'https://www.powerplaycebu.com/schedules',website:'https://www.powerplaycebu.com/schedules',source:'Cebu Pickleball Courts',verified:'2026-09-10'},
 'Magnum Sports Complex':{phone:'0915 461 2097 / 273 0325 / 272 8269',email:'booking@magnumsportscomplex.com',fb:'https://www.facebook.com/p/Magnum-Sports-Complex-61574882055158/',booking:'https://magnumsportscomplex.com/contact/',website:'https://magnumsportscomplex.com/contact/',source:'Cebu Pickleball Courts',verified:'2026-09-10',notes:'₱350/hr weekday 6–10 AM; ₱500/hr weekday 10 AM–10 PM and weekends 6 AM–10 PM.'},
 'Linkers Pickleball Court':{phone:'0933 219 7365',fb:'https://www.facebook.com/p/Linkers-Pickleball-Court-61564986929389/',booking:'https://www.dinky.ph/courts/linkers-pickleball-court',website:'https://sites.google.com/view/linkers-pickleball-court/home',source:'Dinky + Picklers',verified:'2026-09-10'},
 'Game Changer Mandaue':{phone:'0945 140 9914 / 0926 705 0494',email:'gamechangersportsfacility@gmail.com',fb:'https://www.facebook.com/gamechangersportsfacility/',instagram:'https://www.instagram.com/gamechangersportsfacility/',booking:'https://www.dinky.ph/courts/game-changer-sports-facility',source:'Cebu Pickleball Courts + Dinky',verified:'2026-09-10'},
 'Fervent Academy':{phone:'0998 594 0510',fb:'https://www.facebook.com/profile.php?id=61582557202059',source:'Cebu Pickleball Courts',verified:'2026-09-10'},
 'CEH-ABC Gym':{phone:'0938 907 7449',fb:'https://www.facebook.com/cehsportscomplex',source:'Cebu Pickleball Courts',verified:'2026-09-10'},
 'The Courtside Cebu':{phone:'0966 521 4081 / 0930 392 0719',email:'courtsidecebu@gmail.com',fb:'https://www.facebook.com/The-Courtside-Cebu-61580521050375/',booking:'https://www.thecourtsidecebu.com/',website:'https://www.thecourtsidecebu.com/',source:'The Courtside Cebu official site',verified:'2026-09-10',notes:'4 indoor courts: 2 silica sand-coated concrete + 2 cushioned rubber mat courts. Free parking and restroom.'},
 'Mactan Pickleball Club':{phone:'0917 149 1999',fb:'https://www.facebook.com/people/Mactan-Pickleball-Club-OPC/61585580331159/',source:'Cebu Pickleball Courts',verified:'2026-09-10'},
 'HillHouse Liloan':{phone:'0917 156 1630',fb:'https://www.facebook.com/hillhouseburgersnwings/',source:'Cebu Pickleball Courts + KudosCourts',verified:'2026-09-10'},
 'Pickle Yard — Cebu':{phone:'0962 527 5707',email:'pickleyardcebu@gmail.com',booking:'https://pickleyardcebu.com/',website:'https://pickleyardcebu.com/',source:'Pickle Yard official site',verified:'2026-09-10',notes:'1 premium covered court with instant online booking and scheduled open play.'},
 'SOotK Pickleball Hub (Stay Out of the Kitchen!)':{phone:'0917 702 4668',fb:'https://www.facebook.com/profile.php?id=61590346576835',booking:'https://www.dinky.ph/courts/sootk',source:'Dinky + Picklers',verified:'2026-09-10'},
 'PickleShatt Court':{phone:'+63 917 709 5622',booking:'https://www.sports360.ph/',source:'Cebu Pickle',verified:'2026-09-10'},
 'BTC Pickleball Lapu-Lapu':{phone:'0917 321 5781',fb:'https://www.facebook.com/BTCbankal',source:'Pickleheads + PickleBoard',verified:'2026-09-10'}
};
for(const [name,extra] of Object.entries(detailOverrides)){const v=venues.find(x=>x.name===name);if(v)Object.assign(v,extra)}

const state={search:'',region:'cebu',areas:new Set(),price:null,keys:new Set(),sort:'recommended',theme:localStorage.getItem('pp-theme')||'dark'};
const $=id=>document.getElementById(id);
function areas(){return [...new Set(venues.filter(v=>v.region===state.region).map(v=>v.area))].sort();}
function money(v){return v.price==null?'Check venue':`₱${v.price.toLocaleString()}/${v.unit.includes('player')?'player':'hr'}`}
const label={indoor:'Indoor',outdoor:'Outdoor',aircon:'Aircon',lights:'Night lights',parking:'Parking',paddleRental:'Paddle rental',openPlay:'Open play',cafe:'Food / café'};
function link(labelText,url,primary=false){return url?`<a class="${primary?'primary-btn':'secondary-btn'}" target="_blank" rel="noopener noreferrer" href="${url}">${labelText}</a>`:''}
function card(v){const map=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(v.name+' '+v.address)}`;return `<article class="card"><div class="card-top"><div><span class="area">${v.area}</span><h3>${v.name}</h3></div>${v.featured?'<span class="featured">Featured</span>':''}</div><div class="details"><span>🏟 <b>${v.courts}</b> courts</span><span>💸 <b>${money(v)}</b></span><span>⏰ ${v.hours}</span>${v.rating?`<span>★ <b>${v.rating}</b></span>`:''}</div><div class="tags">${v.tags.map(t=>`<span>${label[t]||t}</span>`).join('')}</div><p class="address">${v.address}</p>${v.notes?`<p class="venue-note">${v.notes}</p>`:''}<div class="card-actions">${link('Maps',map,true)}${link('Facebook',v.fb)}${link('Book / Schedule',v.booking)}${v.phone?`<a class="secondary-btn" href="tel:${v.phone.replace(/[^+\d]/g,'')}">Call</a>`:''}</div></article>`}
function details(v){const map=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(v.name+' '+v.address)}`;$('modalContent').innerHTML=`<div class="modal-header"><div><span class="area">${v.area}</span><h2 id="modalTitle">${v.name}</h2></div><button class="icon-btn" id="modalClose" type="button" aria-label="Close">×</button></div><div class="modal-grid"><div><span class="modal-label">Address</span><p>${v.address}</p><a class="text-link" target="_blank" rel="noopener noreferrer" href="${map}">Open Google Maps ↗</a></div><div><span class="modal-label">Court setup</span><p>${v.courts} courts · ${v.tags.includes('indoor')&&v.tags.includes('outdoor')?'Indoor + outdoor':v.tags.includes('indoor')?'Indoor':'Outdoor'}</p></div><div><span class="modal-label">Price</span><p>${money(v)}</p></div><div><span class="modal-label">Hours</span><p>${v.hours}</p></div><div><span class="modal-label">Phone</span><p>${v.phone?`<a class="text-link" href="tel:${v.phone.replace(/[^+\d]/g,'')}">${v.phone}</a>`:'Not publicly listed'}</p></div><div><span class="modal-label">Email</span><p>${v.email?`<a class="text-link" href="mailto:${v.email}">${v.email}</a>`:'Not publicly listed'}</p></div><div class="modal-wide"><span class="modal-label">Links</span><div class="modal-links">${link('Facebook',v.fb)}${link('Instagram',v.instagram)}${link('Booking / Schedule',v.booking)}${link('Website',v.website)}</div></div><div class="modal-wide"><span class="modal-label">Amenities</span><div class="tags">${v.tags.map(t=>`<span>${label[t]||t}</span>`).join('')}</div></div>${v.notes?`<div class="modal-wide"><span class="modal-label">Notes</span><p>${v.notes}</p></div>`:''}<div class="modal-wide"><span class="modal-label">Data status</span><p>${v.source||'Starter directory data'}${v.verified?` · checked ${v.verified}`:''}</p></div></div>`;$('detailsModal').hidden=false;document.body.classList.add('modal-open');$('modalClose').onclick=closeDetails}
function closeDetails(){$('detailsModal').hidden=true;document.body.classList.remove('modal-open')}
function render(){const list=venues.filter(v=>{if(state.region!=='all'&&v.region!==state.region)return false;if(state.search&&!(v.name+' '+v.area+' '+v.address).toLowerCase().includes(state.search.toLowerCase()))return false;if(state.areas.size&&!state.areas.has(v.area))return false;if(state.price!==null&&(v.price==null||v.price>state.price))return false;for(const k of state.keys)if(!v.tags.includes(k))return false;return true}).sort((a,b)=>state.sort==='price-low'?(a.price??99999)-(b.price??99999):state.sort==='price-high'?(b.price??-1)-(a.price??-1):state.sort==='courts-high'?b.courts-a.courts:state.sort==='name'?a.name.localeCompare(b.name):(b.featured?1:0)-(a.featured?1:0)||(b.rating??0)-(a.rating??0));$('results').innerHTML=list.map(card).join('');$('empty').hidden=list.length>0;$('resultMeta').textContent=`${list.length} venue${list.length===1?'':'s'} found · ${state.region==='all'?'Philippines':state.region==='cebu'?'Cebu':'selected region'}`;$('filterSummary').textContent=activeCount()?`${activeCount()} filters active`:'';$('stats').innerHTML=`<div><b>${venues.filter(v=>v.region==='cebu').length}</b><span>Cebu venues</span></div><div><b>${venues.filter(v=>v.region!=='cebu').length}</b><span>PH starter venues</span></div>`;$('areaChips').innerHTML=areas().map(a=>`<button class="chip ${state.areas.has(a)?'active':''}" data-area="${a}">${a}</button>`).join('')||'<span class="muted">Choose a region</span>';document.querySelectorAll('[data-area]').forEach(b=>b.onclick=()=>{state.areas.has(b.dataset.area)?state.areas.delete(b.dataset.area):state.areas.add(b.dataset.area);render()});document.querySelectorAll('[data-details]').forEach(b=>b.onclick=()=>{const v=venues.find(x=>x.name===decodeURIComponent(b.dataset.details));if(v)details(v)})}
function activeCount(){return(state.search?1:0)+(state.areas.size?1:0)+(state.price!==null?1:0)+state.keys.size+(state.region!=='cebu'?1:0)}
document.querySelectorAll('[data-price]').forEach(b=>b.onclick=()=>{const val=Number(b.dataset.price);state.price=state.price===val?null:val;document.querySelectorAll('[data-price]').forEach(x=>x.classList.toggle('active',Number(x.dataset.price)===state.price));render()});document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{const k=b.dataset.key;state.keys.has(k)?state.keys.delete(k):state.keys.add(k);b.classList.toggle('active',state.keys.has(k));render()});$('search').oninput=e=>{state.search=e.target.value;render()};$('region').onchange=e=>{state.region=e.target.value;state.areas.clear();render()};$('sort').onchange=e=>{state.sort=e.target.value;render()};$('resetBtn').onclick=$('emptyReset').onclick=()=>{state.search='';state.region='cebu';state.areas.clear();state.price=null;state.keys.clear();state.sort='recommended';$('search').value='';$('region').value='cebu';$('sort').value='recommended';document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));render()};$('themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';localStorage.setItem('pp-theme',state.theme);document.documentElement.dataset.theme=state.theme;$('themeBtn').textContent=state.theme==='dark'?'☼':'☾'};$('locateBtn').onclick=()=>{if(!navigator.geolocation)return alert('Location is not available in this browser.');navigator.geolocation.getCurrentPosition(()=>alert('Location access is ready. Distance sorting can be added next.'),()=>alert('Please allow location access to enable nearby sorting.'))};$('detailsModal').addEventListener('click',e=>{if(e.target.id==='detailsModal')closeDetails()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetails()});document.documentElement.dataset.theme=state.theme;$('themeBtn').textContent=state.theme==='dark'?'☼':'☾';render();